// Zimbabwe Provinces and Districts
export const ZIMBABWE_PROVINCES = [
  'Bulawayo',
  'Harare',
  'Manicaland',
  'Mashonaland Central',
  'Mashonaland East',
  'Mashonaland West',
  'Masvingo',
  'Matabeleland North',
  'Matabeleland South',
  'Midlands',
] as const;

export const ZIMBABWE_DISTRICTS: Record<string, string[]> = {
  'Bulawayo': [
    'Bulawayo',
  ],
  'Harare': [
    'Harare',
  ],
  'Manicaland': [
    'Buhera',
    'Chimanimani',
    'Chipinge',
    'Makoni',
    'Mutare',
    'Mutasa',
    'Nyanga',
    'Rusape',
  ],
  'Mashonaland Central': [
    'Bindura',
    'Centenary',
    'Guruve',
    'Mazowe',
    'Mount Darwin',
    'Muzarabani',
    'Rushinga',
    'Shamva',
  ],
  'Mashonaland East': [
    'Chikomba',
    'Goromonzi',
    'Marondera',
    'Mudzi',
    'Murehwa',
    'Mutoko',
    'Seke',
    'Uzumba-Maramba-Pfungwe',
    'Wedza',
  ],
  'Mashonaland West': [
    'Chegutu',
    'Hurungwe',
    'Kariba',
    'Makonde',
    'Mhondoro-Ngezi',
    'Sanyati',
    'Zvimba',
    'Kadoma',
  ],
  'Masvingo': [
    'Bikita',
    'Chiredzi',
    'Chivi',
    'Gutu',
    'Masvingo',
    'Mwenezi',
    'Zaka',
  ],
  'Matabeleland North': [
    'Binga',
    'Bubi',
    'Hwange',
    'Lupane',
    'Nkayi',
    'Tsholotsho',
    'Umguza',
  ],
  'Matabeleland South': [
    'Beitbridge',
    'Bulilima',
    'Gwanda',
    'Insiza',
    'Mangwe',
    'Matobo',
    'Umzingwane',
  ],
  'Midlands': [
    'Chirumhanzu',
    'Gokwe North',
    'Gokwe South',
    'Gweru',
    'Kwekwe',
    'Mberengwa',
    'Shurugwi',
    'Zvishavane',
  ],
};

// Crop Categories
export const CROP_CATEGORIES = [
  'Vegetables',
  'Fruits',
  'Grains',
  'Legumes',
  'Roots & Tubers',
  'Herbs & Spices',
  'Other',
] as const;

// Common Crops in Zimbabwe
export const CROP_TYPES: Record<string, string[]> = {
  'Vegetables': [
    'Cabbage',
    'Tomato',
    'Onion',
    'Carrot',
    'Green Beans',
    'Peas',
    'Spinach',
    'Lettuce',
    'Cucumber',
    'Pumpkin',
    'Butternut',
    'Okra',
    'Eggplant',
    'Pepper (Sweet)',
    'Chili Pepper',
    'Broccoli',
    'Cauliflower',
    'Kale',
    'Rape',
    'Covo',
  ],
  'Fruits': [
    'Mango',
    'Orange',
    'Banana',
    'Avocado',
    'Papaya',
    'Guava',
    'Lemon',
    'Lime',
    'Watermelon',
    'Muskmelon',
    'Pineapple',
    'Passion Fruit',
    'Apple',
    'Peach',
    'Plum',
  ],
  'Grains': [
    'Maize',
    'Wheat',
    'Sorghum',
    'Millet',
    'Rice',
    'Barley',
  ],
  'Legumes': [
    'Groundnuts (Peanuts)',
    'Sugar Beans',
    'Cowpeas',
    'Soybeans',
    'Bambara Nuts',
    'Green Gram',
  ],
  'Roots & Tubers': [
    'Potato',
    'Sweet Potato',
    'Cassava',
    'Yam',
    'Carrot',
  ],
  'Herbs & Spices': [
    'Basil',
    'Coriander',
    'Mint',
    'Rosemary',
    'Thyme',
    'Ginger',
    'Turmeric',
    'Garlic',
  ],
  'Other': [
    'Sunflower',
    'Cotton',
    'Tobacco',
    'Sugarcane',
  ],
};

export type Province = typeof ZIMBABWE_PROVINCES[number];
export type CropCategory = typeof CROP_CATEGORIES[number];

